#!/usr/bin/env python3
"""
Pack the Crew Roll-Call voice clips (ADR-0016) into a single binary blob for the
Oro Haptic Paddle's external QSPI flash. (Replaces the retired 12 Session Summary
prompts — ADR-0016.)

Output layout (see external_audio.cpp):
  magic 'OROA' | version u16 | count u16 | reserved u32 | count * Entry | payloads

Each Entry (12 bytes):
  u8 eventId, u8 sampleRateCode (0 = 16 kHz), u16 reserved,
  u32 offset_in_blob, u32 sampleCount

Source WAVs come from OroHapticFirmware/voice_prompts_raw/ (generated by
generate_roll_call_clips.py at 16 kHz mono 16-bit). Anything not already in that
format is resampled with ffmpeg.

Run from the firmware/ directory:
    python build_audio_blob.py
"""
import os
import struct
import subprocess
import sys
import wave

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WAV_DIR = os.path.join(SCRIPT_DIR, "OroHapticFirmware", "voice_prompts_raw")
OUT_PATH = os.path.join(SCRIPT_DIR, "audio_blob.bin")

# (filename stem, audioEventId). IDs must match the RollCallClip enum in OroHapticFirmware.ino:
# the firmware reads clip `i` from external id (0x30 + i), so this order is load-bearing.
PROMPTS = [
    ("rc_team_sync",        0x30),
    ("rc_sync",             0x31),
    ("rc_power",            0x32),
    ("rc_pacer",            0x33),
    ("rc_not_measured",     0x34),
    ("rc_rating_poor",      0x35),
    ("rc_rating_good",      0x36),
    ("rc_rating_excellent", 0x37),
    ("rc_power_light",      0x38),
    ("rc_power_moderate",   0x39),
    ("rc_power_strong",     0x3A),
    ("rc_power_maximum",    0x3B),
    ("rc_seat_1",           0x3C),
    ("rc_seat_2",           0x3D),
    ("rc_seat_3",           0x3E),
    ("rc_seat_4",           0x3F),
    ("rc_seat_5",           0x40),
    ("rc_seat_6",           0x41),
    ("rc_canoe_1",          0x42),
    ("rc_canoe_2",          0x43),
    # Session start/end voice prompts (ADR-0017). Packed by their audio-event id so the firmware
    # plays them via externalAudio.playClip(<id>); not part of the 0x30+ roll-call sequence.
    ("session_standby",              0x14),
    ("session_complete",             0x15),
    ("session_standby_for_results",  0x16),
]

HEADER_SIZE = 12              # magic+version+count+reserved
ENTRY_SIZE = 12
INDEX_END = HEADER_SIZE + ENTRY_SIZE * len(PROMPTS)


def find_ffmpeg():
    """Local copy first, then the imageio-ffmpeg bundle, then PATH."""
    local = os.path.join(SCRIPT_DIR, "ffmpeg.exe")
    if os.path.exists(local):
        return local
    try:
        import imageio_ffmpeg
        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        return "ffmpeg"


def is_16k_mono_s16(wav_path):
    with wave.open(wav_path, "rb") as w:
        return w.getnchannels() == 1 and w.getsampwidth() == 2 and w.getframerate() == 16000


def resample_to_16k_mono_pcm(src_wav, dst_wav):
    cmd = [find_ffmpeg(), "-y", "-i", src_wav,
           "-ar", "16000", "-ac", "1", "-sample_fmt", "s16", dst_wav]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"ffmpeg failed for {src_wav}:\n{r.stderr[-400:]}")


def read_pcm_samples(wav_path):
    with wave.open(wav_path, "rb") as w:
        if w.getnchannels() != 1:
            raise RuntimeError(f"{wav_path}: expected mono, got {w.getnchannels()} channels")
        if w.getsampwidth() != 2:
            raise RuntimeError(f"{wav_path}: expected 16-bit (2 bytes), got {w.getsampwidth()} bytes")
        if w.getframerate() != 16000:
            raise RuntimeError(f"{wav_path}: expected 16 kHz, got {w.getframerate()} Hz")
        n = w.getnframes()
        return w.readframes(n), n


def main():
    if not os.path.isdir(WAV_DIR):
        print(f"ERROR: WAV directory not found: {WAV_DIR}", file=sys.stderr)
        sys.exit(1)

    tmp_dir = os.path.join(SCRIPT_DIR, "audio_blob_tmp_16k")
    os.makedirs(tmp_dir, exist_ok=True)

    entries = []
    payloads = []
    cursor = INDEX_END

    for name, event_id in PROMPTS:
        src = os.path.join(WAV_DIR, f"{name}.wav")
        if not os.path.exists(src):
            print(f"ERROR: missing source {src}\n  Run generate_roll_call_clips.py first.", file=sys.stderr)
            sys.exit(1)
        # Already 16 kHz mono 16-bit? Use it directly; otherwise resample with ffmpeg.
        read_path = src
        if not is_16k_mono_s16(src):
            read_path = os.path.join(tmp_dir, f"{name}_16k.wav")
            resample_to_16k_mono_pcm(src, read_path)
        pcm_bytes, sample_count = read_pcm_samples(read_path)
        entry = struct.pack("<BBHII", event_id, 0, 0, cursor, sample_count)
        entries.append(entry)
        payloads.append(pcm_bytes)
        print(f"  0x{event_id:02X} {name:22s} offset=0x{cursor:06X} samples={sample_count} "
              f"({sample_count/16000:.2f}s, {len(pcm_bytes)} B)")
        cursor += len(pcm_bytes)

    header = struct.pack("<4sHHI", b"OROA", 1, len(PROMPTS), 0)
    blob = header + b"".join(entries) + b"".join(payloads)

    with open(OUT_PATH, "wb") as f:
        f.write(blob)
    print(f"\nWrote {OUT_PATH}  total {len(blob)} bytes ({len(blob)/1024:.1f} KB), {len(PROMPTS)} clips")


if __name__ == "__main__":
    main()
